name: habit_checkin_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0


environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  shared:
    path: ../../packages/shared
  network_layer:
    path: ../../packages/network_layer
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
